# Permalinks
permalink:           pretty

# Setup
title:               John Mager
tagline:             A blog
url:                 http://claymager.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:            
  url:              
  email:             

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/claymager

# Gems
gems:
    - jekyll-paginate
    - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
